"""Email sending via Gmail API"""
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional, Dict
import agent.infra.config as config


def send_email_gmail(
    to_email: str,
    subject: str,
    body: str,
    to_name: Optional[str] = None
) -> Dict:
    """
    Send email via Gmail SMTP
    
    Args:
        to_email: Recipient email address
        subject: Email subject line
        body: Email body (can include HTML)
        to_name: Recipient name (optional)
        
    Returns:
        Dictionary with success status and message
    """
    if not config.GMAIL_ADDRESS or not config.GMAIL_APP_PASSWORD:
        return {
            "success": False,
            "error": "Gmail credentials not configured. Set GMAIL_ADDRESS and GMAIL_APP_PASSWORD in .env"
        }
    
    try:
        # Create message
        message = MIMEMultipart("alternative")
        message["Subject"] = subject
        message["From"] = f"{config.SENDER_INFO['name']} <{config.GMAIL_ADDRESS}>"
        
        if to_name:
            message["To"] = f"{to_name} <{to_email}>"
        else:
            message["To"] = to_email
        
        # Add signature to body
        signature = config.EMAIL_SIGNATURE.format(
            sender_name=config.SENDER_INFO['name'],
            sender_title=config.SENDER_INFO['title'],
            company_name=config.YOUR_COMPANY['name'],
            website=config.YOUR_COMPANY['website']
        )
        
        full_body = f"{body}\n\n{signature}"
        
        # Create plain text version
        part = MIMEText(full_body, "plain")
        message.attach(part)
        
        # Create SSL context
        context = ssl.create_default_context()
        
        # Send email
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(config.GMAIL_ADDRESS, config.GMAIL_APP_PASSWORD)
            server.sendmail(config.GMAIL_ADDRESS, to_email, message.as_string())
        
        return {
            "success": True,
            "message": f"Email sent to {to_email}",
            "to_email": to_email,
            "subject": subject
        }
        
    except Exception as e:
        return {
            "success": False,
            "error": f"Failed to send email: {str(e)}",
            "to_email": to_email
        }


def format_personalized_email(
    recipient_name: str,
    company_name: str,
    email_body: str
) -> str:
    """
    Format email with personalization
    
    Args:
        recipient_name: Recipient's first name
        company_name: Their company name
        email_body: The email body from AI
        
    Returns:
        Formatted email with greeting
    """
    # If email already has "Hi" or "Dear", use as-is
    if email_body.strip().startswith(("Hi ", "Dear ", "Hello ")):
        return email_body
    
    # Otherwise add greeting
    greeting = f"Hi {recipient_name}," if recipient_name else "Hi,"
    
    return f"{greeting}\n\n{email_body}"


def create_email_subject(company_name: str, context: str = "") -> str:
    """
    Create a compelling subject line
    
    Args:
        company_name: Target company name
        context: Additional context for subject
        
    Returns:
        Email subject line
    """
    # Let AI generate subject in the future
    # For now, keep it simple and personal
    
    templates = [
        f"Quick question about {company_name}'s sales process",
        f"Thoughts on {company_name}'s growth",
        f"Idea for {company_name}",
        f"Re: {company_name}'s sales team",
    ]
    
    # Simple: use first template for now
    # In production, let Claude choose based on research
    return templates[0]


def validate_email(email: str) -> bool:
    """
    Basic email validation
    
    Args:
        email: Email address to validate
        
    Returns:
        True if valid format
    """
    if not email:
        return False
    
    # Basic checks
    if "@" not in email:
        return False
    
    if "." not in email.split("@")[1]:
        return False
    
    # Check for common invalid patterns
    invalid_patterns = [
        "noreply@",
        "no-reply@",
        "donotreply@",
        "test@",
        "example@"
    ]
    
    email_lower = email.lower()
    for pattern in invalid_patterns:
        if email_lower.startswith(pattern):
            return False
    
    return True


def send_outreach_email(
    contact: Dict,
    email_body: str,
    subject: Optional[str] = None
) -> Dict:
    """
    Send personalized outreach email to a contact
    
    Args:
        contact: Dictionary with contact info (name, email, company)
        email_body: Email body generated by AI
        subject: Optional custom subject line
        
    Returns:
        Result of sending email
    """
    email = contact.get('email')
    
    # Validate email
    if not validate_email(email):
        return {
            "success": False,
            "error": f"Invalid email address: {email}"
        }
    
    # Format email
    first_name = contact.get('first_name', contact.get('name', '').split()[0])
    company_name = contact.get('company', '')
    
    formatted_body = format_personalized_email(first_name, company_name, email_body)
    
    # Create subject if not provided
    if not subject:
        subject = create_email_subject(company_name)
    
    # Send email
    result = send_email_gmail(
        to_email=email,
        subject=subject,
        body=formatted_body,
        to_name=contact.get('name')
    )
    
    return result
